version: '2'

services:
  build_db:
    build:
      context: ./
      dockerfile: Dockerfile
    image: python/datasim/superhero
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env
    command: ["python", "build_db.py"]
    depends_on:
      - redis
  
  superhero_server:
    image: python/datasim/superhero
    environment:
      - REDIS_HOST=redis
      - SERVER_SLEEP=0.2
      - WEBSOCKET_HOST=0.0.0.0
    env_file:
      - .env
    depends_on:
      - redis
    expose:
      - ${WEBSOCKET_PORT}
  
  worker:
    image: python/datasim/superhero
    environment:
      - REDIS_HOST=redis
    command: ["python", "worker.py"]
    depends_on:
      - redis
  
  player:
    image: python/datasim/superhero
    environment:
      - REDIS_HOST=redis
      - WEBSOCKET_HOST=superhero_nginx
      - WEBSOCKET_PORT=8080
    command: ["python", "client.py"]
    depends_on:
      - superhero_server
  
  superhero_nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    env_file:
      - .env
    depends_on:
      - superhero_server
    ports:
      - "8080:8080"

  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
